# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

locale: "en-GB"
title: "Mat Booth"
subtitle: "Eclipse Services"
name: "Mat Booth Ltd"
description: &tagline >-
  Mat Booth is a software engineer providing support, consulting and
  implementation services for Eclipse plug-ins, Eclipse RCP applications
  and OSGi-based products.
url: "https://matbooth.co.uk"
twitter_username: FOSS_mbooth
github_username:  mbooth101

# Themes
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# RSS Feeds
atom_feed:
  path: "/blog/feeds/all.xml"
feed:
  path: "/blog/feeds/all.xml"
  tags:
    path: "/blog/feeds/"

# Blog Archives
tag_archive:
  type: jekyll-archives
  path: "/blog/"
jekyll-archives:
  enabled:
    - year
    - tags
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/:name/'
  layouts:
    year: year-archive
    tag: tag-archive

# Page and Blog Post Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      tagline: *tagline
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      read_time: true
      show_date: true

# Site Author
author:
  name: "Mat Booth"
  avatar: "/assets/images/hackergotchi-mbooth.png"
  bio: "Professional ones and zeroes plumber and open source advocate. Amateur DIY and tool enthusiast."
  location: "Sheffield, UK"
  email: "info@matbooth.co.uk"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/FOSS_mbooth"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mbooth101"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/FOSS_mbooth"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mbooth101"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:info@matbooth.co.uk"

# Plug-ins
whitelist: []
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Reading Files
include:
  - .htaccess
  - _pages

# Serving
detach: false
port: 4000
host: 0.0.0.0
baseurl: ""
show_dir_listing: false

